<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows7</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NuGet.Versioning" Version="7.0.0" />
    <PackageReference Include="Serilog" Version="4.4.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <ProjectReference Include="..\GeekFlashToolX.Core\GeekFlashToolX.Core.csproj" />
    <PackageReference Include="Avalonia" Version="12.1.1" />
  </ItemGroup>
</Project>
